src/Entity/CategorySection.php
<?php

namespace App\Entity;

use App\Repository\CategorySectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorySectionRepository::class)
 * @ORM\EntityListeners({"App\Doctrine\GenerateCategorySectionAlias"})
 */
class CategorySection
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="section_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category_id;

    /**
     * @ORM\OneToMany(targetEntity=Subcategory::class, mappedBy="category_section_id", orphanRemoval=true)
     */
    private $subcategory_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alias;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $menu_name;

    public function __construct()
    {
        $this->subcategory_id = new ArrayCollection();
    }

    public function __toString(){
        return (string) $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategoryId(): ?Category
    {
        return $this->category_id;
    }

    public function setCategoryId(?Category $category_id): self
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * @return Collection|Subcategory[]
     */
    public function getSubcategoryId(): Collection
    {
        return $this->subcategory_id;
    }

    public function addSubcategoryId(Subcategory $subcategoryId): self
    {
        if (!$this->subcategory_id->contains($subcategoryId)) {
            $this->subcategory_id[] = $subcategoryId;
            $subcategoryId->setCategorySectionId($this);
        }

        return $this;
    }

    public function removeSubcategoryId(Subcategory $subcategoryId): self
    {
        if ($this->subcategory_id->removeElement($subcategoryId)) {
            // set the owning side to null (unless already changed)
            if ($subcategoryId->getCategorySectionId() === $this) {
                $subcategoryId->setCategorySectionId(null);
            }
        }

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(?string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getMenuName(): ?string
    {
        return $this->menu_name;
    }

    public function setMenuName(?string $menu_name): self
    {
        $this->menu_name = $menu_name;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 * @ORM\EntityListeners({"App\Doctrine\GenerateServiceAlias"})
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $h1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Subcategory::class, inversedBy="service")
     */
    private $subcategory_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_img;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alias;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text_hidden;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $header_img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getH1(): ?string
    {
        return $this->h1;
    }

    public function setH1(string $h1): self
    {
        $this->h1 = $h1;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSubcategoryId(): ?Subcategory
    {
        return $this->subcategory_id;
    }

    public function setSubcategoryId(?Subcategory $subcategory_id): self
    {
        $this->subcategory_id = $subcategory_id;

        return $this;
    }

    public function getSeoImg(): ?string
    {
        return $this->seo_img;
    }

    public function setSeoImg(?string $seo_img): self
    {
        $this->seo_img = $seo_img;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getSeoText(): ?string
    {
        return $this->seo_text;
    }

    public function setSeoText(?string $seo_text): self
    {
        $this->seo_text = $seo_text;

        return $this;
    }

    public function getSeoTextHidden(): ?string
    {
        return $this->seo_text_hidden;
    }

    public function setSeoTextHidden(?string $seo_text_hidden): self
    {
        $this->seo_text_hidden = $seo_text_hidden;

        return $this;
    }

    public function getHeaderImg(): ?string
    {
        return $this->header_img;
    }

    public function setHeaderImg(?string $header_img): self
    {
        $this->header_img = $header_img;

        return $this;
    }
}

src/Entity/Subcategory.php
<?php

namespace App\Entity;

use App\Repository\SubcategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SubcategoryRepository::class)
 * @ORM\EntityListeners({"App\Doctrine\GenerateSubCategoryAlias"})
 */
class Subcategory
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $h1;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $seo_img;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="subcategory")
     */
    private $parent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alias;

    /**
     * @ORM\ManyToOne(targetEntity=CategorySection::class, inversedBy="subcategory_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category_section_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text_hidden;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="subcategory_id")
     */
    private $service;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $header_img;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $menu_name;

    public function __construct()
    {
        $this->service = new ArrayCollection();
    }

    public  function __toString(){
        return (string) $this->getH1();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getH1(): ?string
    {
        return $this->h1;
    }

    public function setH1(string $h1): self
    {
        $this->h1 = $h1;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSeoText(): ?string
    {
        return $this->seo_text;
    }

    public function setSeoText(?string $seo_text): self
    {
        $this->seo_text = $seo_text;

        return $this;
    }

    public function getSeoImg(): ?string
    {
        return $this->seo_img;
    }

    public function setSeoImg(?string $seo_img): self
    {
        $this->seo_img = $seo_img;

        return $this;
    }

    public function getParent(): ?Category
    {
        return $this->parent;
    }

    public function setParent(?Category $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getCategorySectionId(): ?CategorySection
    {
        return $this->category_section_id;
    }

    public function setCategorySectionId(?CategorySection $category_section_id): self
    {
        $this->category_section_id = $category_section_id;

        return $this;
    }

    public function getSeoTextHidden(): ?string
    {
        return $this->seo_text_hidden;
    }

    public function setSeoTextHidden(?string $seo_text_hidden): self
    {
        $this->seo_text_hidden = $seo_text_hidden;

        return $this;
    }

    /**
     * @return Collection|Service[]
     */
    public function getService(): Collection
    {
        return $this->service;
    }

    public function addService(Service $service): self
    {
        if (!$this->service->contains($service)) {
            $this->service[] = $service;
            $service->setSubcategoryId($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->service->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getSubcategoryId() === $this) {
                $service->setSubcategoryId(null);
            }
        }

        return $this;
    }

    public function getHeaderImg(): ?string
    {
        return $this->header_img;
    }

    public function setHeaderImg(?string $header_img): self
    {
        $this->header_img = $header_img;

        return $this;
    }

    public function getMenuName(): ?string
    {
        return $this->menu_name;
    }

    public function setMenuName(?string $menu_name): self
    {
        $this->menu_name = $menu_name;

        return $this;
    }
}

templates/pages/category.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ page.h1 }} недорого в Москве и Московской области | Мебельная фабрика Abugera{% endblock %}
{% block description %}⭐⭐⭐⭐⭐ {{ page.h1 }} в Москве и Московской области от Российского производителя Abugera. ✅ Собственная фабрика мебели. ✅ Гарантия 2 года. ✅ Опыт работы более 10 лет. 📌 {{ page.h1 }} рассчитать стоимость - +7(926)825-50-55{% endblock %}
{% block header %}
    {{ render(controller('App\\Widget\\TopMenu::show')) }}
{% endblock %}

    {% block header_fixed %}
        {{ render(controller('App\\Widget\\TopMenu::showFixed')) }}
    {% endblock %}

    {% block header_banner %}
        {{ include('elements/header-banner.html.twig',{'h1' : page.h1, 'headerImg' : page.headerImg, 'shortHeader' : shortHeader}) }}
    {% endblock %}

    {% block body %}
        <!--CATALOG PROD-->
        {{ include ('elements/catalog-prod.html.twig', {'categorySections': categorySections})}}


        {# SEO TEXT#}
        {{ include ('elements/seo_text.html.twig', {'page': page}) }}

        <!-- ADVANTAGES -->
        {{ include ('elements/advantages.html.twig')}}

        <!--WORKS EXAMPLES-->
        {{ include ('elements/works-examples.html.twig', {'seoImg': page.seoImg})}}


        <!--ADVANTAGES-2-->
        {#{{ include ('elements/advantages2.html.twig')}}#}

        <!--PHOTO GALLERY-->
        {#{{ include ('elements/photogallery.html.twig')}}#}
    {% endblock %}

templates/pages/service.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {{ render(controller('App\\Widget\\TopMenu::show')) }}
{% endblock %}

    {% block header_fixed %}
        {{ render(controller('App\\Widget\\TopMenu::showFixed')) }}
    {% endblock %}

    {% block header_banner %}
        {{ include('elements/header-banner.html.twig',{'h1' : page.h1, 'headerImg' : page.headerImg, 'shortHeader' : shortHeader}) }}
    {% endblock %}

    {% block body %}


        <!--ABOUT-->
        {{ include ('elements/about_service.html.twig', {'seoText': page.seoText})}}
        {{ include('elements/popup/two_buttons_block.html.twig') }}


        <!-- ADVANTAGES -->
        {{ include ('elements/advantages.html.twig')}}

        <!--CATALOG PROD-->
        {{ include ('elements/catalog-prod-services.html.twig', {'services': services, 'sectionName': 'Вам может быть интересно', 'categoryPath': page.subcategoryId.categorySectionId.categoryId.alias})}}


        <!--PHOTO GALLERY-->
        {{ include ('elements/photogallery.html.twig')}}
    {% endblock %}

templates/pages/sub_category.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ page.h1 }} недорого в Москве и Московской области | Мебельная фабрика Abugera{% endblock %}
{% block description %}⭐⭐⭐⭐⭐ {{ page.h1 }} в Москве и Московской области от Российского производителя Abugera. ✅ Собственная фабрика мебели. ✅ Гарантия 2 года. ✅ Опыт работы более 10 лет. 📌 {{ page.h1 }} рассчитать стоимость - +7(926)825-50-55{% endblock %}

{% block header %}
    {{ render(controller('App\\Widget\\TopMenu::show')) }}
{% endblock %}

    {% block header_fixed %}
        {{ render(controller('App\\Widget\\TopMenu::showFixed')) }}
    {% endblock %}

    {% block header_banner %}
        {{ include('elements/header-banner.html.twig',{'h1' : page.h1, 'headerImg' : page.categorySectionId.categoryId.headerImg, 'shortHeader' : shortHeader}) }}
    {% endblock %}

    {% block body %}


        {# SEO TEXT#}
        {{ include ('elements/seo_text.html.twig', {'page': page}) }}

        <!-- ADVANTAGES -->
        {{ include ('elements/advantages.html.twig')}}

        <!--WORKS EXAMPLES-->
        {{ include ('elements/works-examples.html.twig', {'seoImg': page.seoImg})}}

        <!--CATALOG PROD-->
        {{ include ('elements/catalog-prod-services.html.twig', {'services': subcategories, 'sectionName': page.categorySectionId.name, 'categoryPath': page.categorySectionId.categoryId.alias})}}


        <!--ADVANTAGES-2-->
        {#{{ include ('elements/advantages2.html.twig')}}#}

        <!--PHOTO GALLERY-->
       {# {{ include ('elements/photogallery.html.twig')}}#}
    {% endblock %}