src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 * @ORM\EntityListeners({"App\Doctrine\GenerateCategoryAlias"})
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $h1;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $seo_img;

    /**
     * @ORM\OneToMany(targetEntity=Subcategory::class, mappedBy="parent")
     */
    private $subcategory;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alias;

    /**
     * @ORM\OneToMany(targetEntity=CategorySection::class, mappedBy="category_id", orphanRemoval=true)
     */
    private $section_id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text_hidden;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $header_img;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $menu_img;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $menu_name;

    public function __construct()
    {
        $this->subcategory = new ArrayCollection();
        $this->section_id = new ArrayCollection();
    }

    public function __toString(){
        return (string) $this->getH1();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getH1(): ?string
    {
        return $this->h1;
    }

    public function setH1(string $h1): self
    {
        $this->h1 = $h1;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSeoText(): ?string
    {
        return $this->seo_text;
    }

    public function setSeoText(?string $seo_text): self
    {
        $this->seo_text = $seo_text;

        return $this;
    }

    public function getSeoImg(): ?string
    {
        return $this->seo_img;
    }

    public function setSeoImg(?string $seo_img): self
    {
        $this->seo_img = $seo_img;

        return $this;
    }

    /**
     * @return Collection|Subcategory[]
     */
    public function getSubcategory(): Collection
    {
        return $this->subcategory;
    }

    public function addSubcategory(Subcategory $subcategory): self
    {
        if (!$this->subcategory->contains($subcategory)) {
            $this->subcategory[] = $subcategory;
            $subcategory->setParent($this);
        }

        return $this;
    }

    public function removeSubcategory(Subcategory $subcategory): self
    {
        if ($this->subcategory->removeElement($subcategory)) {
            // set the owning side to null (unless already changed)
            if ($subcategory->getParent() === $this) {
                $subcategory->setParent(null);
            }
        }

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * @return Collection|CategorySection[]
     */
    public function getSectionId(): Collection
    {
        return $this->section_id;
    }

    public function addSectionId(CategorySection $sectionId): self
    {
        if (!$this->section_id->contains($sectionId)) {
            $this->section_id[] = $sectionId;
            $sectionId->setCategoryId($this);
        }

        return $this;
    }

    public function removeSectionId(CategorySection $sectionId): self
    {
        if ($this->section_id->removeElement($sectionId)) {
            // set the owning side to null (unless already changed)
            if ($sectionId->getCategoryId() === $this) {
                $sectionId->setCategoryId(null);
            }
        }

        return $this;
    }

    public function getSeoTextHidden(): ?string
    {
        return $this->seo_text_hidden;
    }

    public function setSeoTextHidden(?string $seo_text_hidden): self
    {
        $this->seo_text_hidden = $seo_text_hidden;

        return $this;
    }

    public function getHeaderImg(): ?string
    {
        return $this->header_img;
    }

    public function setHeaderImg(?string $header_img): self
    {
        $this->header_img = $header_img;

        return $this;
    }

    public function getMenuImg(): ?string
    {
        return $this->menu_img;
    }

    public function setMenuImg(?string $menu_img): self
    {
        $this->menu_img = $menu_img;

        return $this;
    }

    public function getMenuName(): ?string
    {
        return $this->menu_name;
    }

    public function setMenuName(?string $menu_name): self
    {
        $this->menu_name = $menu_name;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 * @ORM\EntityListeners({"App\Doctrine\GenerateServiceAlias"})
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $h1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Subcategory::class, inversedBy="service")
     */
    private $subcategory_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_img;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alias;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $seo_text_hidden;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $header_img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getH1(): ?string
    {
        return $this->h1;
    }

    public function setH1(string $h1): self
    {
        $this->h1 = $h1;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSubcategoryId(): ?Subcategory
    {
        return $this->subcategory_id;
    }

    public function setSubcategoryId(?Subcategory $subcategory_id): self
    {
        $this->subcategory_id = $subcategory_id;

        return $this;
    }

    public function getSeoImg(): ?string
    {
        return $this->seo_img;
    }

    public function setSeoImg(?string $seo_img): self
    {
        $this->seo_img = $seo_img;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getSeoText(): ?string
    {
        return $this->seo_text;
    }

    public function setSeoText(?string $seo_text): self
    {
        $this->seo_text = $seo_text;

        return $this;
    }

    public function getSeoTextHidden(): ?string
    {
        return $this->seo_text_hidden;
    }

    public function setSeoTextHidden(?string $seo_text_hidden): self
    {
        $this->seo_text_hidden = $seo_text_hidden;

        return $this;
    }

    public function getHeaderImg(): ?string
    {
        return $this->header_img;
    }

    public function setHeaderImg(?string $header_img): self
    {
        $this->header_img = $header_img;

        return $this;
    }
}

templates/elements/about.html.twig
<div class="container-fluid about__block_wrapper">
    <div class="container about__block">
    <div class="about__block_bg"></div>

    <div class="about__block_text">
        <hr data-aos="fade-down" data-aos-duration="2000">
        <h2 data-aos="fade-down" data-aos-duration="2000">О НАС</h2>

        <div class="about__block_media-mobile">
            <div uk-slider class="uk-slider-about">
                <ul class="uk-slider-items uk-child-width-1-1@s uk-grid">
                    <li>
                        <video data-aos="fade-right" controls width="386" height="232"  name="media" poster="{{ asset('images/video-bg.jpg') }}">
                            <source src="video/video-about.mp4?autoplay=false" type="video/mp4">
                        </video>
                    </li>
                    <li>
                        <img data-aos="fade-right" data-fancybox="gallery" src="{{ asset('images/about-img1.jpg') }}" alt="">
                    </li>
                    <li>
                        <img data-aos="fade-right" data-fancybox="gallery" src="{{ asset('images/about-img2.jpg') }}" alt="">
                    </li>
                    <li>
                        <img data-aos="fade-right" data-fancybox="gallery" src="{{ asset('images/about-img3.jpg') }}" alt="">
                    </li>
                </ul>
                <div class="uk-visible">
                    <a class="uk-position-center-left-out" style="left: 0" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
                    <a class="uk-position-center-right-out" style="left: 90%" href="#" uk-slidenav-next uk-slider-item="next"></a>
                </div>
            </div>

        </div>
<div class="about__text">
        <p data-aos="fade-down" data-aos-duration="2000">Компания ABUGERA Workshop основана
            в 2015 году, и сегодня у нас работает уже
            более 10 человек: столяры, маляр, технолог-
            конструктор, монтажники, водитель
            и руководитель производства. Мы сильно
            выросли за последний год, но за быстрым
            ростом очень стараемся сохранить
            высокое качество нашей продукции.</p>

        <p data-aos="fade-down" data-aos-duration="2000">Основная наша ценность – это заботливое
            и очень внимательное отношение
            к заказчику, к его идеям и замыслам,
            ну и конечно, к готовому продукту.</p>

        <p data-aos="fade-down" data-aos-duration="2000">Цель нашей компании – создавать продукт,
            который будет радовать своего владельца:
            качеством исполнения, надежностью
            использования, долгим сроком службы.
            Мы ждем Ваших проектов и всегда
            готовы к открытому и плодотворному
            сотрудничеству. До встречи!</p>
</div>
        <!-- Текст для мобильных (с 935px) -->
        <div class="load-more-container about__text_mobile">

                <p>Компания ABUGERA Workshop основана
                    в 2015 году, и сегодня у нас работает уже
                    более 10 человек: столяры, маляр, технолог-
                    конструктор, монтажники, водитель
                    и руководитель производства. Мы сильно
                    выросли за последний год, но за быстрым
                    ростом очень стараемся сохранить
                    высокое качество нашей продукции.</p>
            <div class="about__show-more">
                <p>Основная наша ценность – это заботливое
                    и очень внимательное отношение
                    к заказчику, к его идеям и замыслам,
                    ну и конечно, к готовому продукту.</p>
                <p>Цель нашей компании – создавать продукт,
                    который будет радовать своего владельца:
                    качеством исполнения, надежностью
                    использования, долгим сроком службы.
                    Мы ждем Ваших проектов и всегда
                    готовы к открытому и плодотворному
                    сотрудничеству. До встречи!</p>
            </div>

            <label class="load-more-btn" for="load-more">
                <span class="unloaded">Ещё</span>
                <span class="loaded">Свернуть</span>
            </label>
        </div>



    </div>

    <div uk-slider class="about__block_media">
        <ul class="uk-slider-items uk-child-width-1-1@l uk-grid">
        <div class="about__carousel_slide">
            <div class="about__block_media-left d-flex flex-column">
                <div class="drop__video">
                    <video data-aos="fade-right" data-aos-duration="2000" controls="" width="386" height="232" name="media" poster="{{ asset('images/video-bg.jpg') }}">
                        <source src="/video/video-about.mp4?autoplay=false" type="video/mp4">
                    </video>
                </div>
                <div data-aos="fade-right" data-aos-duration="2000" class="d-flex align-items-center justify-content-between about__images">
                    <img  data-fancybox="gallery" src="{{ asset('images/about-img1.jpg') }}" alt="">
                    <img data-fancybox="gallery" src="{{ asset('images/about-img2.jpg') }}" alt="">
                </div>
            </div>
            <div data-aos="fade-right" data-aos-duration="2000" class="about__block_media-right">
                <img data-fancybox="gallery" src="{{ asset('images/about-img3.jpg') }}" alt="">
            </div>
        </div>
        <div class="about__carousel_slide ">
            <div class="about__block_media-left d-flex flex-column">
                <div class="drop__video">
                    <video controls="" width="386" height="232" name="media" poster="{{ asset('images/video-bg.jpg') }}">
                        <source src="video/video-about.mp4?autoplay=false" type="video/mp4">
                    </video>
                </div>
                <div class="d-flex align-items-center justify-content-between about__images">
                    <img  data-fancybox="gallery" src="{{ asset('images/about-img1-2.jpg') }}" alt="">
                    <img data-fancybox="gallery" src="{{ asset('images/about-img2-2.jpg') }}" alt="">
                </div>
            </div>
            <div class="about__block_media-right">
                <img data-fancybox="gallery" src="{{ asset('images/about-img3-2.jpg') }}" alt="">
            </div>
        </div>
        </ul>
        <div class="uk-visible">
            <a class="uk-position-center-left-out"  href="#" uk-slidenav-previous uk-slider-item="previous"></a>
            <a class="uk-position-center-right-out"  href="#" uk-slidenav-next uk-slider-item="next"></a>
        </div>
    </div>

    </div>

</div>

templates/elements/advantages.html.twig
<a style="display:block; height: 20px" id="advantages"></a>
<div class="container advantages__block">
    <div class="advantage__block_text">
        <h2 data-aos="fade-up" data-aos-duration="2000">НАШИ ГЛАВНЫЕ <br>ПРЕИМУЩЕСТВА НА РЫНКЕ</h2>
        <p data-aos="fade-up" data-aos-duration="2000">
            Просмотрите наш каталог – здесь выставлены примеры
            популярных моделей. Выбирайте понравившуюся
            и присылайте нам – сделаем по вашим индивидуальным
            размерам - по запросу заменим материал, цвет,
            конструктив или фурнитуру.
        </p>
    </div>
    <div data-aos="fade-up" data-aos-duration="2000" class="advantage__block_items">
        <div class="advantage__block_item">
            <img src="{{ asset('images/adv-icon1.png') }}" alt="" class="hvr-bounce-in">
            <h3>собственная <br>фабрика мебели</h3>
            <p>Возьмём на себя реализацию
                проекта и освободим ваше
                время </p>
        </div>
        <div data-aos="fade-up" data-aos-duration="2000" class="advantage__block_item">
            <img src="{{ asset('images/adv-icon2.png') }}" alt="" class="hvr-bounce-in">
            <h3>опыт работы <br>10 лет</h3>
            <p>За плечами наших замерщиков
                и дизайнеров более 1500
                реализованных проектов</p>
        </div>
        <div data-aos="fade-up" data-aos-duration="2000" class="advantage__block_item">
            <img src="{{ asset('images/adv-icon3.png') }}" alt="" class="hvr-bounce-in">
            <h3>гарантия на мебель <br>2 года</h3>
            <p>Качественные материалы, точные
                размеры - основа надежности
                и долговечности нашей мебели</p>
        </div>
        <div data-aos="fade-up" data-aos-duration="2000" class="advantage__block_item">
            <img src="{{ asset('images/adv-icon4.png') }}" alt="" class="hvr-bounce-in">
            <h3>выгодные цены <br>от производителя</h3>
            <p>У вас есть чертеж или картинка?
                Озвучим стоимость и предложим
                лучшее решение</p>
        </div>
    </div>
</div>

templates/elements/catalog-prod-services.html.twig
<div class="container catalog-prod__block">
{% if services is defined and services is not empty %}


        <div class="catalog-prod__block_menu">
            <div class="catalog-prod__block_menu_content">
                <hr>
                <p class="catalog-prod__block_menu_title">
                    {{ sectionName }}
                </p>
                <div class="buttons-group__desktop">
                    <div class="button-with-circle">
                        <div class="circle"></div>
                        <button class="catalog-menu__btn"><a href="/{{ categoryPath }}"> Перейти в раздел</a></button>
                    </div>
                    <div class="button-with-circle">
                        <div class="circle"></div>
                        <button class="catalog-menu__btn" data-bs-toggle="modal" data-bs-target="#callback_popup">Консультация</button>
                    </div>
                    <div class="button-with-circle">
                        <div class="circle"></div>
                        <button class="catalog-menu__btn" data-bs-toggle="modal" data-bs-target="#callback_popup">Вызвать замерщика</button>
                    </div>
                </div>

            </div>

            <div class="catalog-prod__block_menu_slider">
                <div uk-slider>

                    <div class="uk-position-relative">
                        <div class="uk-slider-container uk-light">
                            <ul class="uk-slider-items {% if services|length < 4 %} uk-child-width-1-{{ services|length }}@l {% else %} uk-child-width-1-4@l {% endif %}
                            uk-child-width-1-2@m uk-child-width-1-1@s">
                                {% for service in services %}
                                    <li>
                                        <a href="/{{ service.alias }}" class="black-linear-bg"></a>
                                    <div class="catalog-prod__slider_link" href="#">
                                        {% if service.seoImg is null %}
                                            <img  data-aos="flip-up" data-aos-duration="1000"  style="width: 250px" src="{{ asset('images/catalog-prod_1_1.jpg')}}" alt="">
                                        {% else %}
                                            <img  data-aos="flip-up" data-aos-duration="1000"  style="width: 250px" src="/images/seo-text-images/{{ service.seoImg }}" alt="{{ service.h1 }}">
                                        {% endif %}
                                        <div class="catalog-prod__slider_img-title">
                                            <hr>
                                            <span><a href="/{{ service.alias }}">{{ service.h1 }}</a> </span>
                                        </div>
                                    </div>
                                </li>
                               {% endfor %}
                            </ul>
                        </div>


                        <div class="uk-visible">
                            <a class="uk-position-center-left-out uk-position-small" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
                            <a class="uk-position-center-right-out uk-position-small" href="#" uk-slidenav-next uk-slider-item="next"></a>
                        </div>

                    </div>



                </div>
                <div class="buttons-group__mobile">
                    <div class="button-with-circle">
                        <div class="circle"></div>
                        <button class="catalog-menu__btn"><a href="/{{ categoryPath }}"> Перейти в раздел</a></button>
                    </div>
                    <div class="button-with-circle">
                        <div class="circle"></div>
                        <button class="catalog-menu__btn" data-bs-toggle="modal" data-bs-target="#callback_popup">Консультация</button>
                    </div>
                    <div class="button-with-circle">
                        <div class="circle"></div>
                        <button class="catalog-menu__btn" data-bs-toggle="modal" data-bs-target="#callback_popup">Вызвать замерщика</button>
                    </div>
                </div>
            </div>
        </div>




{% endif %}

</div>

templates/elements/header-banner.html.twig
<div class="container-fluid header-banner {% if shortHeader is defined and shortHeader == 1 %}header-banner-short{% endif %}" {% if headerImg is defined and headerImg is not null %}style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),url('/images/header_images/{{ headerImg }}')" {% endif %}>
    <div class="header-banner__content">
        {% if h1 is defined %}
            <h1>{{ h1}} <span>в Москве</span></h1>
        {% else %}
        <h1><span>Собственное производство</span> мебели и предметов интерьера <span>в Москве</span></h1>
        {% endif %}
        <div class="button-with-circle">
            <div class="circle"></div>
            <button class="header-banner__btn" data-bs-toggle="modal" data-bs-target="#callback_popup">Консультация</button>
        </div>
    </div>
    <div class="block1__content__arrow hide_mobile">
        <a href="#advantages" id="scroll_button">
            <img class="b-lazy b-loaded" alt="arrow" src="{{ asset('images/arrow.png') }}">
        </a>
    </div>
</div>

templates/elements/seo_text.html.twig
{% if mainPage is defined %}
    <section class="seo__text container-fluid">
        <div class="seo-block">
            <div class="container">
                <div class="row">
                    <div class="seo-left col-md-6 ">
                        <h2>Производство мебели</h2>
                        <p>Более 10 лет мастера фабрики ABUGERA Workshop занимаются созданием мебели первоклассного качества для оснащения жилых, муниципальных, коммерческих помещений. Производство мебели осуществляется из высококачественных материалов, первоклассного сырья на оснащенной новейшим оборудованием собственной площадке.</p>
                        <h3>Какую мебель производят в компании</h3>
                        <p>Клиенты компании по производству мебели могут заказать разнообразные предметы интерьера, в том числе:</p>

                    </div>

                        <div class="seo-right col-md-6 d-flex justify-content-center ">
                            <img class="seo-block__img" src="/images/seo-text-images/stolyarnoe-seo.jpg" alt="*">
                        </div>


                    <div class="seo-left col-12">
                        <div class="seo-text-none">
                            <ul>
                                <li class="li__sign">кухни;</li>
                                <li class="li__sign">кухни;</li>
                                <li class="li__sign">прихожие;</li>
                                <li class="li__sign">корпусную мебель;</li>
                                <li class="li__sign">все для детских комнат;</li>
                                <li class="li__sign">столы и шкафы в офис;</li>
                                <li class="li__sign">мебель для оснащения детских дошкольных и других учреждений;</li>
                                <li class="li__sign">корпусные шкафы и стеллажи.</li>
                            </ul>
                            <p>Ассортимент изделий практически не ограничен. В каждом отдельном случае детали заказа обсуждаются индивидуально. Предметы интерьера обходятся недорого. Смета затрат составляется до того, как заказ передается на производство.</p>
                            <p class="vazno">изготовленная на заказ мебель превосходно выполняет возложенные на нее функции. Созданная по согласованным с заказчиком параметрам, она идеально встает на отведенное для нее место.</p>
                            <h3>Преимущества для клиентов</h3>
                            <p>Клиентам компании по производству мебели доступны следующие возможности:</p>
                            <ul>
                                <li class="li__sign">покупка сочетающихся с интерьером изделий по ценам производителя;</li>
                                <li class="li__sign">выбор стиля и материала;</li>
                                <li class="li__sign">индивидуальный подход;</li>
                                <li class="li__sign">доступная стоимость;</li>
                                <li class="li__sign">соблюдение озвученных в момент оформления заказа сроков изготовления;</li>
                                <li class="li__sign">первоклассное качество, функциональность и длительный срок службы предметов интерьера.</li>
                            </ul>
                            <p>Производство мебели — сложный, непрерывный процесс. Начинается он с разработки дизайна, выбора материалов и фурнитуры. Когда эти вопросы решены, заказ передается на производственную линию.</p>
                            <p class="vazno">на производстве мебели работают мастера с многолетним опытом. Это означает, что результат работ полностью оправдывает ожидания заказчика.</p>
                            <p>Чтобы заказать мебель по индивидуальным параметрам, звоните на фабрику мебели ABUGERA по указанному на сайте контактному телефону или оставляйте заявку на обратный звонок. Есть услуга по доставке в Москве.</p>
                        </div>

                            {{ include ('elements/popup/three_buttons_block.html.twig', {'readMore': true}) }}

                    </div>

                </div>
            </div>
        </div>
    </section>

{% else %}
    {% if page.seoText is not empty and page.seoText is not null %}
    <section class="seo__text container-fluid">
        <div class="seo-block">
            <div class="container">
                <div class="row">
                    <div class="seo-left {% if page.seoImg is not null %}col-md-6 {% else %}col-md-12{% endif %}">
                        {{ page.seoText|raw }}
                    </div>
                    {% if page.seoImg is not null %}
                    <div class="seo-right col-md-6 d-flex justify-content-center ">
                        <img class="seo-block__img" src="/images/seo-text-images/{{ page.seoImg }}" alt="*">
                    </div>
                    {% endif %}

                    <div class="seo-left col-12">
                        {% if page.seoTextHidden is not null %}
                            <div class="seo-text-none">
                                {{ page.seoTextHidden|raw }}
                            </div>
                        {% endif %}
                        {#<div class="seo-btn mbtn">Читать далее</div>#}
                        {% if page.seoTextHidden is not null %}
                            {{ include ('elements/popup/three_buttons_block.html.twig', {'readMore': true}) }}
                        {% else %}
                            {{ include ('elements/popup/three_buttons_block.html.twig', {'readMore': false}) }}
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </section>

        {% else %}
        {# Убрать на prod #}
            <section class="seo__text container-fluid">
                <div class="seo-block">
                    <div class="container">
                        <div class="row">
                            <div class="seo-left {% if page.seoImg is not null %}col-md-6 {% else %}col-md-12{% endif %}">
                                <h2>Текст заглушка просто для демонстрации на стр., где текст не заполнен через админку. На продакшн уберем.</h2>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                            </div>
                            {% if page.seoImg is not null %}
                                <div class="seo-right col-md-6 d-flex justify-content-center ">
                                    <img class="seo-block__img" src="/images/seo-text-images/{{ page.seoImg }}" alt="*">
                                </div>
                            {% endif %}

                            <div class="seo-left col-12">
                                <div class="seo-text-none">
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                                </div>
                                {#<div class="seo-btn mbtn">Читать далее</div>#}
                                {{ include ('elements/popup/three_buttons_block.html.twig') }}
                            </div>

                        </div>
                    </div>
                </div>
            </section>
    {% endif %}

{% endif %}